name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: DEV
    strategy:
      max-parallel: 4
      matrix:
        python-versions: [3.7,3.8,3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd Quote_django
        touch .env
        echo SECRET_KEY=sevretpassword >>.env
        echo Quote_Api_key=${{ secret.Quote_Api_Key }} >>.env
        cat .env
        python manage.py test
